/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppMedsRouteImport } from './routes/_app/meds'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppCareRouteImport } from './routes/_app/care'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTransactionsTransactionIdRouteImport } from './routes/_app/transactions/$transactionId'
import { Route as AppSettingsScheduleRouteImport } from './routes/_app/settings/schedule'
import { Route as AppSettingsPeopleRouteImport } from './routes/_app/settings/people'
import { Route as AppSettingsLovedOneRouteImport } from './routes/_app/settings/loved-one'
import { Route as AppActivityActivityIdRouteImport } from './routes/_app/activity/$activityId'
import { Route as AppAccountsNewRouteImport } from './routes/_app/accounts/new'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppAccountsAccountIdIndexRouteImport } from './routes/_app/accounts/$accountId/index'
import { Route as AppAccountsAccountIdSettingsRouteImport } from './routes/_app/accounts/$accountId/settings'
import { Route as AppAccountsAccountIdTransfersNewRouteImport } from './routes/_app/accounts/$accountId/transfers/new'
import { Route as AppAccountsAccountIdTransactionsNewRouteImport } from './routes/_app/accounts/$accountId/transactions/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppMedsRoute = AppMedsRouteImport.update({
  id: '/meds',
  path: '/meds',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCareRoute = AppCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsTransactionIdRoute =
  AppTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AppTransactionsRoute,
  } as any)
const AppSettingsScheduleRoute = AppSettingsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPeopleRoute = AppSettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLovedOneRoute = AppSettingsLovedOneRouteImport.update({
  id: '/loved-one',
  path: '/loved-one',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppActivityActivityIdRoute = AppActivityActivityIdRouteImport.update({
  id: '/$activityId',
  path: '/$activityId',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppAccountsNewRoute = AppAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountIdIndexRoute =
  AppAccountsAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppAccountsAccountIdSettingsRoute =
  AppAccountsAccountIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppAccountsAccountIdTransfersNewRoute =
  AppAccountsAccountIdTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppAccountsAccountIdTransactionsNewRoute =
  AppAccountsAccountIdTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/activity': typeof AppActivityRouteWithChildren
  '/care': typeof AppCareRoute
  '/documents': typeof AppDocumentsRoute
  '/insights': typeof AppInsightsRoute
  '/invoices': typeof AppInvoicesRoute
  '/meds': typeof AppMedsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/accounts/$accountId': typeof AppAccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AppAccountsNewRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
  '/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/settings/people': typeof AppSettingsPeopleRoute
  '/settings/schedule': typeof AppSettingsScheduleRoute
  '/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/activity/': typeof AppActivityIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/transactions/': typeof AppTransactionsIndexRoute
  '/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/accounts/$accountId/': typeof AppAccountsAccountIdIndexRoute
  '/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/care': typeof AppCareRoute
  '/documents': typeof AppDocumentsRoute
  '/insights': typeof AppInsightsRoute
  '/invoices': typeof AppInvoicesRoute
  '/meds': typeof AppMedsRoute
  '/schedule': typeof AppScheduleRoute
  '/': typeof AppIndexRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
  '/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/settings/people': typeof AppSettingsPeopleRoute
  '/settings/schedule': typeof AppSettingsScheduleRoute
  '/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/activity': typeof AppActivityIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdIndexRoute
  '/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/activity': typeof AppActivityRouteWithChildren
  '/_app/care': typeof AppCareRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/meds': typeof AppMedsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRouteWithChildren
  '/_app/accounts/new': typeof AppAccountsNewRoute
  '/_app/activity/$activityId': typeof AppActivityActivityIdRoute
  '/_app/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/_app/settings/people': typeof AppSettingsPeopleRoute
  '/_app/settings/schedule': typeof AppSettingsScheduleRoute
  '/_app/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/_app/accounts/$accountId/': typeof AppAccountsAccountIdIndexRoute
  '/_app/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/_app/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/accounts'
    | '/activity'
    | '/care'
    | '/documents'
    | '/insights'
    | '/invoices'
    | '/meds'
    | '/schedule'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/activity/$activityId'
    | '/settings/loved-one'
    | '/settings/people'
    | '/settings/schedule'
    | '/transactions/$transactionId'
    | '/api/auth/$'
    | '/accounts/'
    | '/activity/'
    | '/settings/'
    | '/transactions/'
    | '/accounts/$accountId/settings'
    | '/accounts/$accountId/'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transfers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/care'
    | '/documents'
    | '/insights'
    | '/invoices'
    | '/meds'
    | '/schedule'
    | '/'
    | '/accounts/new'
    | '/activity/$activityId'
    | '/settings/loved-one'
    | '/settings/people'
    | '/settings/schedule'
    | '/transactions/$transactionId'
    | '/api/auth/$'
    | '/accounts'
    | '/activity'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId/settings'
    | '/accounts/$accountId'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transfers/new'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/login'
    | '/_app/accounts'
    | '/_app/activity'
    | '/_app/care'
    | '/_app/documents'
    | '/_app/insights'
    | '/_app/invoices'
    | '/_app/meds'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/new'
    | '/_app/activity/$activityId'
    | '/_app/settings/loved-one'
    | '/_app/settings/people'
    | '/_app/settings/schedule'
    | '/_app/transactions/$transactionId'
    | '/api/auth/$'
    | '/_app/accounts/'
    | '/_app/activity/'
    | '/_app/settings/'
    | '/_app/transactions/'
    | '/_app/accounts/$accountId/settings'
    | '/_app/accounts/$accountId/'
    | '/_app/accounts/$accountId/transactions/new'
    | '/_app/accounts/$accountId/transfers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meds': {
      id: '/_app/meds'
      path: '/meds'
      fullPath: '/meds'
      preLoaderRoute: typeof AppMedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care': {
      id: '/_app/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AppCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions/$transactionId': {
      id: '/_app/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AppTransactionsTransactionIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/settings/schedule': {
      id: '/_app/settings/schedule'
      path: '/schedule'
      fullPath: '/settings/schedule'
      preLoaderRoute: typeof AppSettingsScheduleRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/people': {
      id: '/_app/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof AppSettingsPeopleRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/loved-one': {
      id: '/_app/settings/loved-one'
      path: '/loved-one'
      fullPath: '/settings/loved-one'
      preLoaderRoute: typeof AppSettingsLovedOneRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/activity/$activityId': {
      id: '/_app/activity/$activityId'
      path: '/$activityId'
      fullPath: '/activity/$activityId'
      preLoaderRoute: typeof AppActivityActivityIdRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/accounts/new': {
      id: '/_app/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AppAccountsNewRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/$accountId/': {
      id: '/_app/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AppAccountsAccountIdIndexRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/accounts/$accountId/settings': {
      id: '/_app/accounts/$accountId/settings'
      path: '/settings'
      fullPath: '/accounts/$accountId/settings'
      preLoaderRoute: typeof AppAccountsAccountIdSettingsRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/accounts/$accountId/transfers/new': {
      id: '/_app/accounts/$accountId/transfers/new'
      path: '/transfers/new'
      fullPath: '/accounts/$accountId/transfers/new'
      preLoaderRoute: typeof AppAccountsAccountIdTransfersNewRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/accounts/$accountId/transactions/new': {
      id: '/_app/accounts/$accountId/transactions/new'
      path: '/transactions/new'
      fullPath: '/accounts/$accountId/transactions/new'
      preLoaderRoute: typeof AppAccountsAccountIdTransactionsNewRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
  }
}

interface AppAccountsAccountIdRouteChildren {
  AppAccountsAccountIdSettingsRoute: typeof AppAccountsAccountIdSettingsRoute
  AppAccountsAccountIdIndexRoute: typeof AppAccountsAccountIdIndexRoute
  AppAccountsAccountIdTransactionsNewRoute: typeof AppAccountsAccountIdTransactionsNewRoute
  AppAccountsAccountIdTransfersNewRoute: typeof AppAccountsAccountIdTransfersNewRoute
}

const AppAccountsAccountIdRouteChildren: AppAccountsAccountIdRouteChildren = {
  AppAccountsAccountIdSettingsRoute: AppAccountsAccountIdSettingsRoute,
  AppAccountsAccountIdIndexRoute: AppAccountsAccountIdIndexRoute,
  AppAccountsAccountIdTransactionsNewRoute:
    AppAccountsAccountIdTransactionsNewRoute,
  AppAccountsAccountIdTransfersNewRoute: AppAccountsAccountIdTransfersNewRoute,
}

const AppAccountsAccountIdRouteWithChildren =
  AppAccountsAccountIdRoute._addFileChildren(AppAccountsAccountIdRouteChildren)

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRouteWithChildren
  AppAccountsNewRoute: typeof AppAccountsNewRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRouteWithChildren,
  AppAccountsNewRoute: AppAccountsNewRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppActivityRouteChildren {
  AppActivityActivityIdRoute: typeof AppActivityActivityIdRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
}

const AppActivityRouteChildren: AppActivityRouteChildren = {
  AppActivityActivityIdRoute: AppActivityActivityIdRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
}

const AppActivityRouteWithChildren = AppActivityRoute._addFileChildren(
  AppActivityRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsLovedOneRoute: typeof AppSettingsLovedOneRoute
  AppSettingsPeopleRoute: typeof AppSettingsPeopleRoute
  AppSettingsScheduleRoute: typeof AppSettingsScheduleRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsLovedOneRoute: AppSettingsLovedOneRoute,
  AppSettingsPeopleRoute: AppSettingsPeopleRoute,
  AppSettingsScheduleRoute: AppSettingsScheduleRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTransactionsRouteChildren {
  AppTransactionsTransactionIdRoute: typeof AppTransactionsTransactionIdRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsTransactionIdRoute: AppTransactionsTransactionIdRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppActivityRoute: typeof AppActivityRouteWithChildren
  AppCareRoute: typeof AppCareRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMedsRoute: typeof AppMedsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppActivityRoute: AppActivityRouteWithChildren,
  AppCareRoute: AppCareRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMedsRoute: AppMedsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
