/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRequestRouteImport } from './routes/verify-request'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppShoppingRouteImport } from './routes/_app/shopping'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppMedsRouteImport } from './routes/_app/meds'
import { Route as AppMealsRouteImport } from './routes/_app/meals'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppCareRouteImport } from './routes/_app/care'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTransactionsNewRouteImport } from './routes/_app/transactions/new'
import { Route as AppTransactionsTransactionIdRouteImport } from './routes/_app/transactions/$transactionId'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsTagsRouteImport } from './routes/_app/settings/tags'
import { Route as AppSettingsScheduleRouteImport } from './routes/_app/settings/schedule'
import { Route as AppSettingsPeopleRouteImport } from './routes/_app/settings/people'
import { Route as AppSettingsPayeesRouteImport } from './routes/_app/settings/payees'
import { Route as AppSettingsLovedOneRouteImport } from './routes/_app/settings/loved-one'
import { Route as AppSettingsDocumentTypesRouteImport } from './routes/_app/settings/document-types'
import { Route as AppSettingsCategoriesRouteImport } from './routes/_app/settings/categories'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/_app/documents/$documentId'
import { Route as AppActivityActivityIdRouteImport } from './routes/_app/activity/$activityId'
import { Route as AppAccountsNewRouteImport } from './routes/_app/accounts/new'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppSettingsUsersIndexRouteImport } from './routes/_app/settings/users/index'
import { Route as AppAccountsAccountIdIndexRouteImport } from './routes/_app/accounts/$accountId/index'
import { Route as AppTransactionsTransfersNewRouteImport } from './routes/_app/transactions/transfers/new'
import { Route as AppSettingsUsersUserIdRouteImport } from './routes/_app/settings/users/$userId'
import { Route as AppAccountsAccountIdSettingsRouteImport } from './routes/_app/accounts/$accountId/settings'
import { Route as AppAccountsAccountIdTransfersNewRouteImport } from './routes/_app/accounts/$accountId/transfers/new'
import { Route as AppAccountsAccountIdTransactionsNewRouteImport } from './routes/_app/accounts/$accountId/transactions/new'

const VerifyRequestRoute = VerifyRequestRouteImport.update({
  id: '/verify-request',
  path: '/verify-request',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMedsRoute = AppMedsRouteImport.update({
  id: '/meds',
  path: '/meds',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCareRoute = AppCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsNewRoute = AppTransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppTransactionsTransactionIdRoute =
  AppTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AppTransactionsRoute,
  } as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTagsRoute = AppSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsScheduleRoute = AppSettingsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPeopleRoute = AppSettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPayeesRoute = AppSettingsPayeesRouteImport.update({
  id: '/payees',
  path: '/payees',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLovedOneRoute = AppSettingsLovedOneRouteImport.update({
  id: '/loved-one',
  path: '/loved-one',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDocumentTypesRoute =
  AppSettingsDocumentTypesRouteImport.update({
    id: '/document-types',
    path: '/document-types',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppActivityActivityIdRoute = AppActivityActivityIdRouteImport.update({
  id: '/$activityId',
  path: '/$activityId',
  getParentRoute: () => AppActivityRoute,
} as any)
const AppAccountsNewRoute = AppAccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppSettingsUsersIndexRoute = AppSettingsUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsUsersRoute,
} as any)
const AppAccountsAccountIdIndexRoute =
  AppAccountsAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppTransactionsTransfersNewRoute =
  AppTransactionsTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AppTransactionsRoute,
  } as any)
const AppSettingsUsersUserIdRoute = AppSettingsUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppSettingsUsersRoute,
} as any)
const AppAccountsAccountIdSettingsRoute =
  AppAccountsAccountIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppAccountsAccountIdTransfersNewRoute =
  AppAccountsAccountIdTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)
const AppAccountsAccountIdTransactionsNewRoute =
  AppAccountsAccountIdTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => AppAccountsAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/verify-request': typeof VerifyRequestRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/activity': typeof AppActivityRouteWithChildren
  '/care': typeof AppCareRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/insights': typeof AppInsightsRoute
  '/invoices': typeof AppInvoicesRoute
  '/meals': typeof AppMealsRoute
  '/meds': typeof AppMedsRoute
  '/notes': typeof AppNotesRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/shopping': typeof AppShoppingRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AppAccountsNewRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/document-types': typeof AppSettingsDocumentTypesRoute
  '/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/settings/payees': typeof AppSettingsPayeesRoute
  '/settings/people': typeof AppSettingsPeopleRoute
  '/settings/schedule': typeof AppSettingsScheduleRoute
  '/settings/tags': typeof AppSettingsTagsRoute
  '/settings/users': typeof AppSettingsUsersRouteWithChildren
  '/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/activity/': typeof AppActivityIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/transactions/': typeof AppTransactionsIndexRoute
  '/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/transactions/transfers/new': typeof AppTransactionsTransfersNewRoute
  '/accounts/$accountId/': typeof AppAccountsAccountIdIndexRoute
  '/settings/users/': typeof AppSettingsUsersIndexRoute
  '/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/verify-request': typeof VerifyRequestRoute
  '/care': typeof AppCareRoute
  '/insights': typeof AppInsightsRoute
  '/invoices': typeof AppInvoicesRoute
  '/meals': typeof AppMealsRoute
  '/meds': typeof AppMedsRoute
  '/notes': typeof AppNotesRoute
  '/schedule': typeof AppScheduleRoute
  '/shopping': typeof AppShoppingRoute
  '/api/files': typeof ApiFilesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/': typeof AppIndexRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/activity/$activityId': typeof AppActivityActivityIdRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/document-types': typeof AppSettingsDocumentTypesRoute
  '/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/settings/payees': typeof AppSettingsPayeesRoute
  '/settings/people': typeof AppSettingsPeopleRoute
  '/settings/schedule': typeof AppSettingsScheduleRoute
  '/settings/tags': typeof AppSettingsTagsRoute
  '/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/activity': typeof AppActivityIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/transactions/transfers/new': typeof AppTransactionsTransfersNewRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdIndexRoute
  '/settings/users': typeof AppSettingsUsersIndexRoute
  '/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/verify-request': typeof VerifyRequestRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/activity': typeof AppActivityRouteWithChildren
  '/_app/care': typeof AppCareRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/insights': typeof AppInsightsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/meds': typeof AppMedsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/shopping': typeof AppShoppingRoute
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRouteWithChildren
  '/_app/accounts/new': typeof AppAccountsNewRoute
  '/_app/activity/$activityId': typeof AppActivityActivityIdRoute
  '/_app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/_app/settings/categories': typeof AppSettingsCategoriesRoute
  '/_app/settings/document-types': typeof AppSettingsDocumentTypesRoute
  '/_app/settings/loved-one': typeof AppSettingsLovedOneRoute
  '/_app/settings/payees': typeof AppSettingsPayeesRoute
  '/_app/settings/people': typeof AppSettingsPeopleRoute
  '/_app/settings/schedule': typeof AppSettingsScheduleRoute
  '/_app/settings/tags': typeof AppSettingsTagsRoute
  '/_app/settings/users': typeof AppSettingsUsersRouteWithChildren
  '/_app/transactions/$transactionId': typeof AppTransactionsTransactionIdRoute
  '/_app/transactions/new': typeof AppTransactionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/accounts/$accountId/settings': typeof AppAccountsAccountIdSettingsRoute
  '/_app/settings/users/$userId': typeof AppSettingsUsersUserIdRoute
  '/_app/transactions/transfers/new': typeof AppTransactionsTransfersNewRoute
  '/_app/accounts/$accountId/': typeof AppAccountsAccountIdIndexRoute
  '/_app/settings/users/': typeof AppSettingsUsersIndexRoute
  '/_app/accounts/$accountId/transactions/new': typeof AppAccountsAccountIdTransactionsNewRoute
  '/_app/accounts/$accountId/transfers/new': typeof AppAccountsAccountIdTransfersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/verify-request'
    | '/accounts'
    | '/activity'
    | '/care'
    | '/documents'
    | '/insights'
    | '/invoices'
    | '/meals'
    | '/meds'
    | '/notes'
    | '/schedule'
    | '/settings'
    | '/shopping'
    | '/transactions'
    | '/api/files'
    | '/api/uploads'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/activity/$activityId'
    | '/documents/$documentId'
    | '/settings/categories'
    | '/settings/document-types'
    | '/settings/loved-one'
    | '/settings/payees'
    | '/settings/people'
    | '/settings/schedule'
    | '/settings/tags'
    | '/settings/users'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/api/auth/$'
    | '/accounts/'
    | '/activity/'
    | '/documents/'
    | '/settings/'
    | '/transactions/'
    | '/accounts/$accountId/settings'
    | '/settings/users/$userId'
    | '/transactions/transfers/new'
    | '/accounts/$accountId/'
    | '/settings/users/'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transfers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/verify-request'
    | '/care'
    | '/insights'
    | '/invoices'
    | '/meals'
    | '/meds'
    | '/notes'
    | '/schedule'
    | '/shopping'
    | '/api/files'
    | '/api/uploads'
    | '/'
    | '/accounts/new'
    | '/activity/$activityId'
    | '/documents/$documentId'
    | '/settings/categories'
    | '/settings/document-types'
    | '/settings/loved-one'
    | '/settings/payees'
    | '/settings/people'
    | '/settings/schedule'
    | '/settings/tags'
    | '/transactions/$transactionId'
    | '/transactions/new'
    | '/api/auth/$'
    | '/accounts'
    | '/activity'
    | '/documents'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId/settings'
    | '/settings/users/$userId'
    | '/transactions/transfers/new'
    | '/accounts/$accountId'
    | '/settings/users'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transfers/new'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/login'
    | '/verify-request'
    | '/_app/accounts'
    | '/_app/activity'
    | '/_app/care'
    | '/_app/documents'
    | '/_app/insights'
    | '/_app/invoices'
    | '/_app/meals'
    | '/_app/meds'
    | '/_app/notes'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/shopping'
    | '/_app/transactions'
    | '/api/files'
    | '/api/uploads'
    | '/_app/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/new'
    | '/_app/activity/$activityId'
    | '/_app/documents/$documentId'
    | '/_app/settings/categories'
    | '/_app/settings/document-types'
    | '/_app/settings/loved-one'
    | '/_app/settings/payees'
    | '/_app/settings/people'
    | '/_app/settings/schedule'
    | '/_app/settings/tags'
    | '/_app/settings/users'
    | '/_app/transactions/$transactionId'
    | '/_app/transactions/new'
    | '/api/auth/$'
    | '/_app/accounts/'
    | '/_app/activity/'
    | '/_app/documents/'
    | '/_app/settings/'
    | '/_app/transactions/'
    | '/_app/accounts/$accountId/settings'
    | '/_app/settings/users/$userId'
    | '/_app/transactions/transfers/new'
    | '/_app/accounts/$accountId/'
    | '/_app/settings/users/'
    | '/_app/accounts/$accountId/transactions/new'
    | '/_app/accounts/$accountId/transfers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  VerifyRequestRoute: typeof VerifyRequestRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-request': {
      id: '/verify-request'
      path: '/verify-request'
      fullPath: '/verify-request'
      preLoaderRoute: typeof VerifyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping': {
      id: '/_app/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meds': {
      id: '/_app/meds'
      path: '/meds'
      fullPath: '/meds'
      preLoaderRoute: typeof AppMedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care': {
      id: '/_app/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AppCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions/new': {
      id: '/_app/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/transactions/$transactionId': {
      id: '/_app/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AppTransactionsTransactionIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tags': {
      id: '/_app/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AppSettingsTagsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/schedule': {
      id: '/_app/settings/schedule'
      path: '/schedule'
      fullPath: '/settings/schedule'
      preLoaderRoute: typeof AppSettingsScheduleRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/people': {
      id: '/_app/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof AppSettingsPeopleRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/payees': {
      id: '/_app/settings/payees'
      path: '/payees'
      fullPath: '/settings/payees'
      preLoaderRoute: typeof AppSettingsPayeesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/loved-one': {
      id: '/_app/settings/loved-one'
      path: '/loved-one'
      fullPath: '/settings/loved-one'
      preLoaderRoute: typeof AppSettingsLovedOneRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/document-types': {
      id: '/_app/settings/document-types'
      path: '/document-types'
      fullPath: '/settings/document-types'
      preLoaderRoute: typeof AppSettingsDocumentTypesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/categories': {
      id: '/_app/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/documents/$documentId': {
      id: '/_app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/activity/$activityId': {
      id: '/_app/activity/$activityId'
      path: '/$activityId'
      fullPath: '/activity/$activityId'
      preLoaderRoute: typeof AppActivityActivityIdRouteImport
      parentRoute: typeof AppActivityRoute
    }
    '/_app/accounts/new': {
      id: '/_app/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AppAccountsNewRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/settings/users/': {
      id: '/_app/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AppSettingsUsersIndexRouteImport
      parentRoute: typeof AppSettingsUsersRoute
    }
    '/_app/accounts/$accountId/': {
      id: '/_app/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AppAccountsAccountIdIndexRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/transactions/transfers/new': {
      id: '/_app/transactions/transfers/new'
      path: '/transfers/new'
      fullPath: '/transactions/transfers/new'
      preLoaderRoute: typeof AppTransactionsTransfersNewRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/settings/users/$userId': {
      id: '/_app/settings/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof AppSettingsUsersUserIdRouteImport
      parentRoute: typeof AppSettingsUsersRoute
    }
    '/_app/accounts/$accountId/settings': {
      id: '/_app/accounts/$accountId/settings'
      path: '/settings'
      fullPath: '/accounts/$accountId/settings'
      preLoaderRoute: typeof AppAccountsAccountIdSettingsRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/accounts/$accountId/transfers/new': {
      id: '/_app/accounts/$accountId/transfers/new'
      path: '/transfers/new'
      fullPath: '/accounts/$accountId/transfers/new'
      preLoaderRoute: typeof AppAccountsAccountIdTransfersNewRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
    '/_app/accounts/$accountId/transactions/new': {
      id: '/_app/accounts/$accountId/transactions/new'
      path: '/transactions/new'
      fullPath: '/accounts/$accountId/transactions/new'
      preLoaderRoute: typeof AppAccountsAccountIdTransactionsNewRouteImport
      parentRoute: typeof AppAccountsAccountIdRoute
    }
  }
}

interface AppAccountsAccountIdRouteChildren {
  AppAccountsAccountIdSettingsRoute: typeof AppAccountsAccountIdSettingsRoute
  AppAccountsAccountIdIndexRoute: typeof AppAccountsAccountIdIndexRoute
  AppAccountsAccountIdTransactionsNewRoute: typeof AppAccountsAccountIdTransactionsNewRoute
  AppAccountsAccountIdTransfersNewRoute: typeof AppAccountsAccountIdTransfersNewRoute
}

const AppAccountsAccountIdRouteChildren: AppAccountsAccountIdRouteChildren = {
  AppAccountsAccountIdSettingsRoute: AppAccountsAccountIdSettingsRoute,
  AppAccountsAccountIdIndexRoute: AppAccountsAccountIdIndexRoute,
  AppAccountsAccountIdTransactionsNewRoute:
    AppAccountsAccountIdTransactionsNewRoute,
  AppAccountsAccountIdTransfersNewRoute: AppAccountsAccountIdTransfersNewRoute,
}

const AppAccountsAccountIdRouteWithChildren =
  AppAccountsAccountIdRoute._addFileChildren(AppAccountsAccountIdRouteChildren)

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRouteWithChildren
  AppAccountsNewRoute: typeof AppAccountsNewRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRouteWithChildren,
  AppAccountsNewRoute: AppAccountsNewRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppActivityRouteChildren {
  AppActivityActivityIdRoute: typeof AppActivityActivityIdRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
}

const AppActivityRouteChildren: AppActivityRouteChildren = {
  AppActivityActivityIdRoute: AppActivityActivityIdRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
}

const AppActivityRouteWithChildren = AppActivityRoute._addFileChildren(
  AppActivityRouteChildren,
)

interface AppDocumentsRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppSettingsUsersRouteChildren {
  AppSettingsUsersUserIdRoute: typeof AppSettingsUsersUserIdRoute
  AppSettingsUsersIndexRoute: typeof AppSettingsUsersIndexRoute
}

const AppSettingsUsersRouteChildren: AppSettingsUsersRouteChildren = {
  AppSettingsUsersUserIdRoute: AppSettingsUsersUserIdRoute,
  AppSettingsUsersIndexRoute: AppSettingsUsersIndexRoute,
}

const AppSettingsUsersRouteWithChildren =
  AppSettingsUsersRoute._addFileChildren(AppSettingsUsersRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsDocumentTypesRoute: typeof AppSettingsDocumentTypesRoute
  AppSettingsLovedOneRoute: typeof AppSettingsLovedOneRoute
  AppSettingsPayeesRoute: typeof AppSettingsPayeesRoute
  AppSettingsPeopleRoute: typeof AppSettingsPeopleRoute
  AppSettingsScheduleRoute: typeof AppSettingsScheduleRoute
  AppSettingsTagsRoute: typeof AppSettingsTagsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRouteWithChildren
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsDocumentTypesRoute: AppSettingsDocumentTypesRoute,
  AppSettingsLovedOneRoute: AppSettingsLovedOneRoute,
  AppSettingsPayeesRoute: AppSettingsPayeesRoute,
  AppSettingsPeopleRoute: AppSettingsPeopleRoute,
  AppSettingsScheduleRoute: AppSettingsScheduleRoute,
  AppSettingsTagsRoute: AppSettingsTagsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRouteWithChildren,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTransactionsRouteChildren {
  AppTransactionsTransactionIdRoute: typeof AppTransactionsTransactionIdRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransactionsTransfersNewRoute: typeof AppTransactionsTransfersNewRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsTransactionIdRoute: AppTransactionsTransactionIdRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransactionsTransfersNewRoute: AppTransactionsTransfersNewRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppActivityRoute: typeof AppActivityRouteWithChildren
  AppCareRoute: typeof AppCareRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMealsRoute: typeof AppMealsRoute
  AppMedsRoute: typeof AppMedsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShoppingRoute: typeof AppShoppingRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppActivityRoute: AppActivityRouteWithChildren,
  AppCareRoute: AppCareRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppInsightsRoute: AppInsightsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMealsRoute: AppMealsRoute,
  AppMedsRoute: AppMedsRoute,
  AppNotesRoute: AppNotesRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShoppingRoute: AppShoppingRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  VerifyRequestRoute: VerifyRequestRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
